import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthContextProvider } from "./firebase/firebaseConfig";
import { Toaster } from "react-hot-toast";
import "./styles/background.scss";
import "./styles/globals.css";
import Script from "next/script";

import BackgroundEffect from "./ui/BackgroundEffect";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Osmoze",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className="flex flex-col min-h-screen">
          <div className="overlay text-xl sm:text-3xl">
            Please open this website on PC or Laptop.
          </div>
          <div className="background-container ">
            <BackgroundEffect />
          </div>
          <div className="children-container ">{children}</div>
          <Script src="script.js"></Script>
        </body>

        <div>
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              success: {
                duration: 2000,
              },
              style: {
                fontSize: "16px",
                maxWidth: "500px",
                padding: "16px 24px",
                backgroundColor: "#fff",
                color: "#374151",
                marginBottom: "3px",
              },
            }}
          />
        </div>
      </AuthContextProvider>
    </html>
  );
}
